export const INITIAL_WORKFLOWS = [
  {
    id: 'wf-1',
    name: 'Customer Support Bot',
    description: 'Classifies and routes incoming support tickets using AI',
    status: 'active',
    createdAt: '2024-01-15',
    nodes: [
      {
        id: 'n1',
        type: 'trigger',
        title: 'Webhook Trigger',
        x: 60,
        y: 80,
        config: { triggerType: 'webhook', url: '/webhook/support' },
      },
      {
        id: 'n2',
        type: 'agent',
        title: 'Intent Classifier',
        x: 340,
        y: 60,
        config: {
          model: 'gpt-4',
          systemPrompt: 'You are an expert support ticket classifier.',
          prompt: 'Classify the user intent from: {{input}}. Categories: billing, technical, general.',
          temperature: 0.3,
        },
      },
      },
      {
        id: 'n4',
        type: 'agent',
        title: 'Billing Agent',
        x: 500,
        y: 280,
        config: {
          model: 'gpt-4',
          prompt: 'Handle billing inquiry: {{input}}',
          temperature: 0.5,
        },
      },
      {
        id: 'n5',
        type: 'output',
        title: 'Send Response',
        x: 800,
        y: 280,
        config: { channel: 'webhook', format: 'json' },
      },
    ],
    edges: [
      { id: 'e1', from: 'n1', to: 'n2' },
      { id: 'e2', from: 'n2', to: 'n3' },
      { id: 'e3', from: 'n3', to: 'n4' },
      { id: 'e4', from: 'n4', to: 'n5' },
    ],
  },
  {
    id: 'wf-2',
    name: 'Data Pipeline',
    description: 'Scheduled data fetch, AI analysis, and email reporting',
    status: 'draft',
    createdAt: '2024-01-18',
    nodes: [
      {
        id: 'n1',
        type: 'trigger',
        title: 'Scheduled Trigger',
        x: 60,
        y: 120,
        config: { triggerType: 'cron', cron: '0 9 * * *' },
      },
      {
        id: 'n2',
        type: 'function',
        title: 'Fetch Data',
        x: 340,
        y: 120,
        config: {
          runtime: 'javascript',
          code: `async (input) => {\n  const res = await fetch(input.url);\n  return res.json();\n}`,
          timeout: 5000,
        },
      },
      {
        id: 'n3',
        type: 'agent',
        title: 'Data Analyzer',
        x: 620,
        y: 120,
        config: {
          model: 'gpt-4',
          prompt: 'Analyze this dataset and provide key insights:\n\n{{data}}',
          temperature: 0.7,
        },
      },
      {
        id: 'n4',
        type: 'output',
        title: 'Email Report',
        x: 900,
        y: 120,
        config: { channel: 'email', to: 'team@company.com', format: 'markdown' },
      },
    ],
    edges: [
      { id: 'e1', from: 'n1', to: 'n2' },
      { id: 'e2', from: 'n2', to: 'n3' },
      { id: 'e3', from: 'n3', to: 'n4' },
    ],
  },
  {
    id: 'wf-3',
    name: 'Content Generator',
    description: 'Blank canvas — build your own workflow',
    status: 'draft',
    createdAt: '2024-01-20',
    nodes: [],
    edges: [],
  },
];
